name: Release

on:
  push:
    branches:
      - master

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Install dependencies
        run: pnpm install

  build:
    name: Build
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      # - name: Run tests
      #   run: npm test

      - name: Build
        run: pnpm build

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
